config/routes.rb
Rails.application.routes.draw do
  resources :reports
  root 'static_public#home'
  devise_for :users
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users

  resources :payments
  get 'user_dash', to: 'static_public#user_dash'
  get 'trems', to: 'static_public#trems'
  get 'payment_status', to: 'payments#payment_status'
  get 'pricing', to: 'static_public#pricing'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/static_public_controller.rb
class StaticPublicController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :trems]
  def home
  end

  def user_dash
  end

  def trems
  end


  def pricing
    @products = Product.all
  end
end

app/views/static_public/home.html.erb
<h1>StaticPublic#home</h1>
<p>Find me in app/views/static_public/home.html.erb</p>
<%= link_to "user dashboard", user_dash_path %>
<%= link_to "home", root_path %>
<%= link_to "trems", trems_path %>

app/views/static_public/pricing.html.erb
<h1> pricing</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <div class="mysr-form"></div>

    <p>
      <%= link_to "Show this product", product %>
    </p>
    
  <% end %>
</div>

app/views/static_public/trems.html.erb
<h1>StaticPublic#trems</h1>
<p>Find me in app/views/static_public/trems.html.erb</p>
<%= link_to "user dashboard", user_dash_path %>
<%= link_to "home", root_path %>
<%= link_to "trems", trems_path %>

app/views/static_public/user_dash.html.erb
<h1>StaticPublic#user_dash</h1>
<p>Find me in app/views/static_public/user_dash.html.erb</p>
<%= link_to "user dashboard", user_dash_path %>
<%= link_to "home", root_path %>
<%= link_to "trems", trems_path %>